### ISSUE TITLE
增加用户能量值

### ISSUE THREAD

**Issue by overtrue** [overtrue/api.yike.io#1]
- 发贴 -20
- 发评论 - 2
- 帖子被赞 + 2
- 评论被赞 + 2
- 评论被踩 - 5
- 删除评论 - 10

**Comment by liuhao25** [comment]
超哥，能量值扣的这么厉害，负数的情况考虑吗？

**Comment by overtrue** [comment]
负数就不让发布内容了

**Comment by liuhao25** [comment]
发一篇帖子减 20 ，这得有 10 个赞才能恢复到正常值，是不是太严苛了，哈哈

**Comment by overtrue** [comment]
每天重置啊
