### ISSUE TITLE
敏感词过滤

### ISSUE THREAD

**Issue by overtrue** [overtrue/api.yike.io#2]
增加敏感词过滤功能，当触发 5 次时发送邮件给管理员，暂停该用户发布权限

**Comment by liuhao25** [comment]
@overtrue 超哥，当用户触发敏感词过滤功能的时候，用缓存记录触发的次数（存的永久的），当触发达到五次的时候给管理员发送邮件通知， 用户发布的时候会通过 ThreadPolicy 检测是否具备发布权限 （也是就是通过检测敏感词触发是否达到五次）。这种方式可行吗，还是说，通过 User settings 设定用户是否有发布权限。

**Comment by overtrue** [comment]
#20
