### ISSUE TITLE
超哥, 反馈个问题哈, 自己域名邮箱一直没收到激活邮件

### ISSUE THREAD

**Issue by oknixus** [overtrue/api.yike.io#26]
邮箱是 nixus at nixus.cn
然后就想换个Gmail的, 重新申请激活邮件, 但是Gmail也没有收到任何邮件

两个邮箱, 垃圾邮件中也找了, 没有

**Comment by overtrue** [comment]
你是说你自己部署的？还是我的 yike.io

Nixus <notifications@github.com>于2019年2月14日 周四下午5:18写道：

**Comment by oknixus** [comment]
是yike.io

**Comment by overtrue** [comment]
队列服务的问题，我来搞定。

**Comment by oknixus** [comment]
已经收到邮件了, 谢谢超哥👍🏻
