### ISSUE TITLE
无限循环执行自动加精

### ISSUE THREAD

**Issue by ivothgle** [overtrue/api.yike.io#28]
https://github.com/overtrue/api.yike.io/blob/cf39809b01638e9ac609f03dfce5b2bacb96569e/app/Thread.php#L94-L96

这里有无限递归
复现：
1）设置 `QUEUE_DRIVER=sync`
2) 查看任意一篇帖子详情
出现 `Maximum function nesting level of '256' reached, aborting!`

原因：
查询帖子触发 Model `retrieved` 事件，调度`ThreadAddPopular`，由于用了 trait `SerializesModels`，执行该任务的时候是先序列化后反序列化，在反序列化过程重会重新根据 id 查一次数据库，再次触发 Model `retrieved` 事件，因此陷入无限循环中无法自拔！

还有就是在查找数据的时候更新数据似乎有点不太好吧，绝大情况下查询执行`ThreadAddPopular`是多余的

PS 这里用了`$this` 是什么情况
https://github.com/overtrue/api.yike.io/blob/cf39809b01638e9ac609f03dfce5b2bacb96569e/app/Thread.php#L142-L144

**Comment by overtrue** [comment]
@liuhao25 锅来啦

**Comment by liuhao25** [comment]
哈哈，我的锅

**Comment by ivothgle** [comment]
其实发现用了`app/Observers/ThreadObserver.php`，要不要把 `\APP\Thread` 的`boot`内容挪过去？
