### ISSUE TITLE
nodes 报错

### ISSUE THREAD

**Issue by JeffreyBool** [overtrue/api.yike.io#67]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."threads_count"' desc, `cache`->'$."subscribers_count"' desc limit 5 offset ' at line 1 (SQL: select * from `nodes` where `node_id` is not null and `nodes`.`deleted_at` is null order by `created_at` desc, `cache`->'$."threads_count"' desc, `cache`->'$."subscribers_count"' desc limit 5 offset 0)

![image](https://user-images.githubusercontent.com/24415888/57578264-39dcf880-74bb-11e9-9679-8b43facce79e.png)

**Comment by overtrue** [comment]
MySQL 5.7.7+ required

JeffreyBool <notifications@github.com>于2019年5月12日 周日下午1:38写道：

**Comment by JeffreyBool** [comment]
谢谢
